### ISSUE TITLE
Generators make Dialyzer complain that a function has no local return

### ISSUE THREAD

**Issue by dimitarvp** [whatyouhide/stream_data#130] opened 2019-06-11 11:53 UTC
Given this code:

```elixir
  @spec optional_alphanum(pos_integer) :: %StreamData{}
  def optional_alphanum(size) when size > 0 do
    gen all str <- string([?A..?Z, ?0..?9], min_length: 0, max_length: size) do
      String.pad_trailing(str, size, " ")
    end
  end
```

Dialyzer says: `Function optional_alphanum/1 has no local return`. I also tried appending `| no_return()` to the return type, and it did not help.

Can we make Dialyzer happy with `ExUnitProperties` / `StreamData` -- and how?

(Copied from https://elixirforum.com/t/property-generators-make-dialyzer-complain-ideas-how-to-make-it-happy/23049)

**Comment by rodrigues** [comment] 2019-06-12 17:43
I also have dialyzer errors with stream_data generators, specifically when I use `gen`.

Generators like this one work fine, no dialyzer issues:

```elixir
  def example, do: non_empty(list_of(atom(:alphanumeric)))
```

But all the ones I use `gen` have errors:

```elixir
  def path do
    gen all parts <- nonempty(list_of(atom(:alphanumeric)) do
      "/#{Enum.join(parts, "/")}"
    end
  end
```


```
test/support/stream_generators.ex:37:no_return
Function path/0 has no local return.
________________________________________________________________________________
test/support/stream_generators.ex:38:call_without_opaque
Function call without opaqueness type mismatch.

Call does not have expected opaque term of type StreamData.t(_) in the 1st position.

StreamData.nonempty(%StreamData{:generator => (_, _ -> map())})
```

**Comment by whatyouhide** [comment] 2019-06-17 21:35
I've narrowed it down to when you call `StreamData.bind_filter/2` (which is what `nonempty/1` ends up calling deep down) with the first argument not being a `%StreamData{}` struct but being for example an atom (which is a valid generator).

That is, this reproduces the same error:

```elixir
bind_filter(:foo, fn _ -> {:cont, integer()} end)
```

No idea why. The spec for `bind_filter` specifies `t(a)` as its first argument and `t(a)` is defined as `%StreamData{} | atom() | tuple()`.

Then, I narrowed it down to this problem: if I leave the spec as

```elixir
@spec bind_filter(t(a), (a -> {:cont, t(b)} | :skip), non_neg_integer()) :: t(b)
      when a: term(),
           b: term()
```

then the Dialyzer warning happens. If I literally copy and paste the contents of `t(a)` to the spec, it magically works.

```elixir
  @spec bind_filter(
          %__MODULE__{generator: generator_fun(a)} | atom() | tuple(),
          (a -> {:cont, t(b)} | :skip),
          non_neg_integer()
        ) :: t(b)
```

I'll never understand Dialyzer.

**Comment by rodrigues** [comment] 2019-06-29 20:42
@whatyouhide I also replaced `t(a)` by its definition, but in my case that didn't have any effect, the `no return` errors are still the same.

**Comment by rodrigues** [comment] 2019-07-12 19:52
Today I've had some time to continue the work on #133, and finally, after fixing the `bind_filter/3` typespecs, now I don't get anymore this error 🕺🏽

**Comment by whatyouhide** [comment] 2019-09-22 15:53
Closing in favor of the PR #133.

**Closed by whatyouhide** 2019-09-22 15:53 UTC

**Comment by axelson** [comment] 2020-02-14 21:15
Since #133 was closed, is there a workaround for this? (for reference I'm working on https://github.com/verypossible/harald/pull/52)

**Comment by whatyouhide** [comment] 2020-02-19 20:16
There isn't and I really would prefer to avoid botching a type spec to make Dialyzer happy. I use type specs for documentation and I don't use Dialyzer myself. If you want to spend some time figuring out if there's a solution that would keep the specs clear and also keep Dialyzer happy, I'd be more than happy to get it in :)
